### ISSUE TITLE
In npm, you wrote the wrong installation method. You wrote npm install tdweb.

### ISSUE THREAD

**Issue by StevenMichael3213** [DIBgram/tdweb#1]
![image](https://user-images.githubusercontent.com/31765462/144314190-ce3b4819-9c82-47f9-af9e-8cf031e97dbb.png)

**Comment by Mammad900** [comment]
@StevenMichael3213 Thanks for the report.

I've already fixed this on GitHub, while the NPM website still has the problem. 

We need to wait until the next version is released, and it will be applied to the NPM package webpage.
