### ISSUE TITLE
move build file to dist/tdweb

### ISSUE THREAD

**Issue by ILG2021** [DIBgram/tdweb#2]
Hello DIBgram, can you change webpack config to package output file to a folder like tdweb, so the files will be like this:
```
dist/tdweb/1.e0d8d673d927d408e89d.worker.js
dist/tdweb/28495f2d748d78bb12a6e6e3242cc696.wasm
dist/tdweb/tdweb.js
```
That will help when I use tdweb in a web app. You can see how telegram react use tdweb now:
https://github.com/evgeny-nadymov/telegram-react/tree/master/public
The tdweb files are not in a folder, so when I need to replace tdweb, it is not convenient.

**Comment by Mammad900** [comment]
> That will help when I use tdweb in a web app. You can see how telegram react use tdweb now:
https://github.com/evgeny-nadymov/telegram-react/tree/master/public
The tdweb files are not in a folder, so when I need to replace tdweb, it is not convenient.

Can you elaborate? How does this change affect the process to upgrade TDLib?
