### ISSUE TITLE
hey, can anyone help me how to use dibgram/tdweb in react, if you can please show me a simple react web app where dibgram/tdweb used

### ISSUE THREAD

**Issue by sbgoud** [DIBgram/tdweb#3]
hey, can anyone help me how to use dibgram/tdweb in react, if you can please show me a simple react web app where dibgram/tdweb used, or if possible build a very simple react webapp where a user can login using telegram credentials and can see his last 5 messages on screen.

**Comment by Mammad900** [comment]
Hi @sbgoud, you can check DIBgram/DIBgram, it is a telegram web app written by me. It's not complete but contains what you are looking for. If that doesn't help, you can check other web apps using this package at https://github.com/DIBgram/tdweb/network/dependents. I hope that helps!
